# Generated by Django 4.2.14 on 2024-07-21 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('a_int', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='administrator',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='administered_business', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_id',
            field=models.CharField(editable=False, max_length=200),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='name')),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Media',
                'unique_together': {('name',)},
            },
        ),
    ]
