# Generated by Django 4.2.14 on 2024-07-22 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_int', '0002_alter_business_administrator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='dcbsiudsbudscbudcbudc', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
