# Generated by Django 4.2.14 on 2024-07-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_int', '0003_product_product_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-pk',)},
        ),
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='f1',
            field=models.FileField(null=True, upload_to='items/%Y/%M'),
        ),
        migrations.AddField(
            model_name='item',
            name='f2',
            field=models.FileField(null=True, upload_to='items/%Y/%M'),
        ),
        migrations.AddField(
            model_name='item',
            name='f3',
            field=models.FileField(null=True, upload_to='items/%Y/%M'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_id',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
