# Generated by Django 4.2.14 on 2024-07-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_int', '0004_alter_product_options_item_color_item_f1_item_f2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='f1',
            field=models.FileField(upload_to='items/%Y/%M'),
        ),
        migrations.AlterField(
            model_name='item',
            name='f2',
            field=models.FileField(upload_to='items/%Y/%M'),
        ),
        migrations.AlterField(
            model_name='item',
            name='f3',
            field=models.FileField(upload_to='items/%Y/%M'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
