# Generated by Django 4.2.14 on 2024-07-29 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a_int', '0007_alter_businesstransactions_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_account', to='a_int.businessaccount'),
        ),
    ]
