# Generated by Django 4.2.14 on 2024-07-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_int', '0008_business_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesstransactions',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='maintransactions',
            name='number',
            field=models.IntegerField(),
        ),
    ]
