# Generated by Django 4.2.14 on 2024-08-01 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_int', '0009_alter_businesstransactions_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesstransactions',
            name='commission',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='businesstransactions',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='businesstransactions',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='maintransactions',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='maintransactions',
            name='is_credited',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='maintransactions',
            name='is_success',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='maintransactions',
            name='item_id',
            field=models.CharField(max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='maintransactions',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='maintransactions',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
